services:
  notifications:
    container_name: ${PROJECT_NAME}_notifications
    hostname: notifications
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file: .env
    ports:
      - "${PORT}:8000"
    volumes:
      - ./src:/src/
    logging:
      driver: "json-file"
      options:
        max-size: 50m
        max-file: "2"
